# Generated by Django 4.1.7 on 2023-03-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='for_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Тип предсавления')),
                ('photo', models.ImageField(blank=True, upload_to='image/For_me/78', verbose_name='Обложка')),
                ('text', models.TextField(blank=True, verbose_name='Описание')),
                ('avail', models.BooleanField(default=True, verbose_name='Активость')),
            ],
            options={
                'verbose_name': 'Обо мне',
                'verbose_name_plural': 'Обо мне',
                'ordering': ('name',),
            },
        ),
    ]
