# Generated by Django 4.1.7 on 2023-05-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_contakts_alter_for_me_photo_alter_images_keys_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contakts',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contakts',
            name='url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='for_me',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/For_me/31', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='images_keys',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/Keys/9417', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='images_nevs',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/Keys/137', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='keys',
            name='logo',
            field=models.ImageField(blank=True, upload_to='image/Keys/1810', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='nevs',
            name='logo',
            field=models.ImageField(blank=True, upload_to='image/Nevs/458', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/Partners/78', verbose_name='Обложка'),
        ),
    ]
