# Generated by Django 4.1.7 on 2023-04-09 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_alter_for_me_photo_alter_images_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images_keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='image/Keys/470', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Дополнительное фото кейсов',
                'verbose_name_plural': 'Дополнительные фото кейса',
            },
        ),
        migrations.CreateModel(
            name='Images_nevs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='image/Keys/8710', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Дополнительное фото новостей',
                'verbose_name_plural': 'Дополнительные фото новости',
            },
        ),
        migrations.RemoveField(
            model_name='nevs',
            name='description',
        ),
        migrations.AlterField(
            model_name='for_me',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/For_me/39', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='keys',
            name='logo',
            field=models.ImageField(blank=True, upload_to='image/Keys/3006', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='nevs',
            name='logo',
            field=models.ImageField(blank=True, upload_to='image/Nevs/1432', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='nevs',
            name='main_text',
            field=models.TextField(blank=True, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/Partners/77', verbose_name='Обложка'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AddField(
            model_name='images_nevs',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainsite.nevs'),
        ),
        migrations.AddField(
            model_name='images_keys',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainsite.keys'),
        ),
    ]
