# Generated by Django 4.1.7 on 2023-05-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_alter_contakts_name_alter_contakts_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contakts',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Активость'),
        ),
        migrations.AlterField(
            model_name='for_me',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/For_me/5', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='images_keys',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/Keys/778', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='images_nevs',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/Keys/672', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='keys',
            name='logo',
            field=models.ImageField(blank=True, upload_to='image/Keys/5829', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='nevs',
            name='logo',
            field=models.ImageField(blank=True, upload_to='image/Nevs/5481', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/Partners/16', verbose_name='Обложка'),
        ),
    ]
