# Generated by Django 4.1.7 on 2023-04-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_images_keys_images_nevs_remove_nevs_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images_nevs',
            options={'verbose_name': 'Дополнительное фото новостей ', 'verbose_name_plural': 'Дополнительные фото новости'},
        ),
        migrations.AlterField(
            model_name='for_me',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/For_me/1', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='images_keys',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/Keys/2579', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='images_nevs',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/Keys/787', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='keys',
            name='logo',
            field=models.ImageField(blank=True, upload_to='image/Keys/4205', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='nevs',
            name='logo',
            field=models.ImageField(blank=True, upload_to='image/Nevs/6102', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/Partners/3', verbose_name='Обложка'),
        ),
    ]
