# Generated by Django 4.1.7 on 2023-04-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_alter_images_nevs_options_alter_for_me_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='for_me',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/For_me/24', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='images_keys',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/Keys/8473', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='images_nevs',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/Keys/6421', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='keys',
            name='logo',
            field=models.ImageField(blank=True, upload_to='image/Keys/4427', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='nevs',
            name='logo',
            field=models.ImageField(blank=True, upload_to='image/Nevs/3245', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/Partners/11', verbose_name='Обложка'),
        ),
    ]
