# Generated by Django 4.1.7 on 2023-03-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_alter_for_me_photo_alter_partners_photo_keys_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Назвение услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Дополнительное фото', 'verbose_name_plural': 'Дополнительные фото'},
        ),
        migrations.AlterField(
            model_name='for_me',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/For_me/72', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/Partners/85', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='keys',
            name='services',
            field=models.ManyToManyField(to='mainsite.services', verbose_name='Услуги'),
        ),
    ]
