# Generated by Django 4.1.7 on 2023-03-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_services_alter_images_options_alter_for_me_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='text',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='for_me',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/For_me/43', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='keys',
            name='description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='keys',
            name='logo',
            field=models.ImageField(blank=True, upload_to='image/Keys/%Y/%m/%d', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/Partners/<django.db.models.fields.CharField>', verbose_name='Обложка'),
        ),
    ]
