# Generated by Django 4.1.7 on 2023-04-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_alter_for_me_photo_alter_images_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zaiavki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Имя')),
                ('svaz', models.TextField(blank=True, verbose_name='Способ связи')),
                ('description', models.TextField(blank=True, verbose_name='Описание заказа')),
                ('status', models.TextField(blank=True, verbose_name='Стастус заявки')),
                ('available', models.BooleanField(default=True, verbose_name='Активость')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='for_me',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/For_me/73', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/Keys/9773', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='keys',
            name='logo',
            field=models.ImageField(blank=True, upload_to='image/Keys/1983', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/Partners/15', verbose_name='Обложка'),
        ),
    ]
