# Generated by Django 4.1.7 on 2023-04-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0012_alter_for_me_photo_alter_images_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nevs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Имя')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дато создания')),
                ('logo', models.ImageField(blank=True, upload_to='image/Nevs/3173', verbose_name='Обложка')),
                ('description', models.TextField(blank=True, verbose_name='Тизер новости')),
                ('main_text', models.TextField(blank=True, verbose_name='Тело новости')),
                ('available', models.BooleanField(default=True, verbose_name='Активость')),
            ],
            options={
                'verbose_name': 'Новсть',
                'verbose_name_plural': 'Новости',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='for_me',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/For_me/21', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/Keys/6419', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='keys',
            name='logo',
            field=models.ImageField(blank=True, upload_to='image/Keys/4042', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/Partners/41', verbose_name='Обложка'),
        ),
    ]
