# Generated by Django 4.1.7 on 2023-04-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_nevs_alter_for_me_photo_alter_images_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='for_me',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/For_me/15', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/Keys/5292', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='keys',
            name='logo',
            field=models.ImageField(blank=True, upload_to='image/Keys/5630', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='nevs',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дато создания'),
        ),
        migrations.AlterField(
            model_name='nevs',
            name='logo',
            field=models.ImageField(blank=True, upload_to='image/Nevs/447', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image/Partners/64', verbose_name='Обложка'),
        ),
    ]
